### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by redbox-cdn** [xdecock/vmod-modsecurity#1]
Hi this vmod is very nice and interesting.

I am facing compile error.
Centos7 varnish6.1 and vmod-modsecurity is 6.1

```
./bootstrap 
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `build-aux'.
libtoolize: copying file `build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
src/Makefile.am:5: error: 'vmod_LTLIBRARIES' is used but 'vmoddir' is undefined
automake: warnings are treated as errors
src/Makefile.am:9: warning: variable 'libvmod_sec_la_SOURCES' is defined but no program or
src/Makefile.am:9: library has 'libvmod_sec_la' as canonical name (possible typo)
src/Makefile.am:10: warning: variable 'nodist_libvmod_sec_la_SOURCES' is defined but no program or
src/Makefile.am:10: library has 'libvmod_sec_la' as canonical name (possible typo)
src/Makefile.am:8: warning: variable 'libvmod_sec_la_LDFLAGS' is defined but no program or
src/Makefile.am:8: library has 'libvmod_sec_la' as canonical name (possible typo)
```

**Comment by xdecock** [comment]
What branches are you using?

**Comment by xdecock** [comment]
Do you have the dev packages for centos? I've built correctly on debian
derived system but don't have a centos at hand.

**Comment by redbox-cdn** [comment]
Hi 

I used 6.1 following branches.
https://github.com/xdecock/vmod-modsecurity/archive/6.1.zip

I do not have dev packages. my varnish is source install.

Therefore I think must define pkgconfig path  before compile but it does not work.

`export PKG_CONFIG_PATH=/usr/local/varnish/lib/pkgconfig/`

/usr/local/varnish/lib/pkgconfig/varnishapi.pc detail is here.
As you can see, vmoddir is defined.

```
prefix=/usr/local/varnish
exec_prefix=${prefix}
bindir=${exec_prefix}/bin
sbindir=${exec_prefix}/sbin
libdir=${exec_prefix}/lib
sysconfdir=${prefix}/etc
pkgsysconfdir=${sysconfdir}/varnish
includedir=${prefix}/include
pkgincludedir=${includedir}/varnish
datarootdir=${prefix}/share
datadir=${datarootdir}
pkgdatadir=${datadir}/varnish
vcldir=${pkgdatadir}/vcl
vmoddir=${libdir}/varnish/vmods
vmodtool=${pkgdatadir}/vmodtool.py
vsctool=${pkgdatadir}/vsctool.py

Name: VarnishAPI
Description: Varnish API
Version: 6.1.1
Cflags: -I${includedir}/varnish
Libs: -L${libdir} -lvarnishapi
```

**Comment by xdecock** [comment]
Do you have a script tonget a centos to this point?

I'll install a cm and try to understand what's the issue here.

It's my first vmod. So i think the api is stable But i suspect the first use cases in the wild will need some work :)

That's the goal

**Comment by redbox-cdn** [comment]
Is this means varnish compile option? 
```

export PKG_CONFIG_PATH=/usr/local/varnish/lib/pkgconfig/
./autogen.sh && ./configure --prefix /usr/local/varnish
make && make install
```

I think this vmod hope very useful and standard in this future!

**Comment by iammeken** [comment]
apt-get install libvarnishapi-dev

Please run this.

**Comment by xdecock** [comment]
Hello, @redbox-cdn , i've updated the source code to 6.4, haven't changed anything linked to libtoolize though, but might be one of the dependency you're missing.

(spent quite some time packaging for debian recently)

**Comment by redbox-cdn** [comment]
Hi thank you for information. I will try this package my developer site.
Best!!
